sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.haxelib-local/

language: scala

scala:
  - 2.11.7
  - 2.10.6

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - mono-devel
    - libgc1c2

before_install:
  - travis_retry wget http://nekovm.org/media/neko-2.0.0-linux64.tar.gz
  - tar zxvf neko-2.0.0-linux64.tar.gz
  - travis_retry wget http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/"$HAXE_FILE"
  - tar zxvf "$HAXE_FILE"
  - mv haxe-*/ haxe/
  - export PATH=$PATH:$PWD/haxe:$PWD/neko-2.0.0-linux
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/neko-2.0.0-linux
  - export HAXE_STD_PATH=$PWD/haxe/std
  - haxelib setup .haxelib-local
  - travis_retry haxelib install hxjava --always
  - travis_retry haxelib install hxparse
  - travis_retry haxelib install continuation
  - travis_retry haxelib install microbuilder-HUGS

script:
  - sbt ";++$TRAVIS_SCALA_VERSION;haxelibInstallDependencies;$SBT_COMMAND"

  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0e11823ea12783811cd8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  matrix:
    # Haxe 3.2.0
    - SBT_COMMAND=test;test:run HAXE_FILE=haxe_2015-05-12_master_77d171b.tar.gz

    # Haxe 3.2.1
    - SBT_COMMAND=test;test:run HAXE_FILE=haxe_2015-10-12_master_deab442.tar.gz
